MODEL:
  PRETRAIN_PATH: '/home/zbc/.torch/models/resnet50-19c8e357.pth'
  
INPUT:
  SIZE_TRAIN: [384, 384]
  SIZE_TEST: [384, 384]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing 
  PADDING: 10

DATASETS:
  NAMES: 'cvwc'
  DATA_PATH: '/home/zbc/data/cvwc/reid'
  TRAIN_PATH: 'local_train'
  QUERY_PATH: 'local_query'
  GALLERY_PATH: 'local_gallery'

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 4

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  BASE_LR: 0.0001
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64
  FP16: True

  STEPS: [20, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 195, 210, 225, 240, 255]
  GAMMA: 0.6

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 1
  LOG_PERIOD: 10
  EVAL_PERIOD: 1

TEST:
  IMS_PER_BATCH: 16
  DEBUG: True
  WEIGHT: "path"

OUTPUT_DIR: "/home/zbc/ReID/outputs/cvwc_local"


